name: DEV-CI/CD
on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona'

jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    name: Continious Integration
    runs-on: ${{matrix.platform}}
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on

    steps:
      # Install go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      # Build code
      - name: Build
        working-directory: ./src/github.com/${{ github.repository }}
        run:  make build
      # Run code
      - name: Run code
        working-directory: ./src/github.com/${{ github.repository }}
        run: make run
        env:
          GREETING: ${{ github.event.inputs.name }}
  cd:
    name: Continious Deployment
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy code
        working-directory: ./src/github.com/${{ github.repository }}
        run: |
          ls -la
          echo "Deploying to DEV"