name: PROD-CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    name: Continous Integration
    runs-on: ${{matrix.platform}}
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on

    steps:
      # Install go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      # Build code
      - name: Build
        working-directory: ./src/github.com/${{ github.repository }}
        run:  make build
      # Run code
      - name: Run code
        working-directory: ./src/github.com/${{ github.repository }}
        run: make run
        env:
          GREETING: ${{ github.event.inputs.name }}
      # Workaround for sharing data between jobs
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./src/github.com/${{ github.repository }}/bin/main
          retention-days: 1
  cd:
    name: Continous Deployment
    runs-on: ubuntu-latest
    needs: ci
    steps:
      # Workaround for sharing data between jobs
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Deploy artifact
        run: |
          ls -la
          echo "Deploying to Prod"