name: golang-action-test
on: push
jobs:
  golang-test-action:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{matrix.platform}}
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - uses: actions/checkout@v2
      # Build code
      - name: Build
        run:  |
          pwd
          ls -la
          cat -e -t -v Makefile
          make build
      # Run code
      - name: Run code
        run: make run
        env:
          GREETING: "from git actions"
