name: golang-action-test
on: push
jobs:
  golang-test-action:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      # Install golang 1.15
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      # Build code
      - name: Build
        run:  |
          go env
          ls -la
          cat -e -t -v Makefile
          make build
      # Run code
      - name: Run code
        run: make run
        env:
          GREETING: "from git actions"
