name: golang-action-test
on: push
jobs:
  golang-test-action:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      # Install golang 1.15 & build
      - name: Install Go & build
        uses: cedrickring/golang-action/go1.15@1.6.0
        with:
          args: make build
      - name: Run code
        run: make run
        env:
          GO111MODULE: "on"
          GREETING: "from git actions"
