name: golang-action-test
on: push
jobs:
  golang-test-action:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{matrix.platform}}
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
      WORKING_DIR: ./src/github.com/${{ github.repository }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - uses: actions/checkout@v2
        with:
          path: ${{WORKING_DIR}}
      # Build code
      - name: Build
        working-directory: ${{WORKING_DIR}}
        run:  make build
      # Run code
      - name: Run code
        working-directory: ${{WORKING_DIR}}
        run: make run
        env:
          GREETING: "from git actions"