name: golang-action-test
on: push
jobs:
  golang-test-action:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{matrix.platform}}
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
      GREETING: "my friend!"

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      # Build code
      - name: Build
        run:  |
          echo ${{ github.workspace }}
          cd ./src/github.com/${{ github.repository }}
          make build
      # Run code
      - name: Run code
        run: |
          cd ./src/github.com/${{ github.repository }}
          make run
        env:
          GREETING: "from git actions"
