name: golang-action-test
on: push
jobs:
  golang-test-action:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Install golang 1.15
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      # Build code
      - name: Build
        run:  |
          go env
          make build
      # Run code
      - name: Run code
        run: make run
        env:
          GREETING: "from git actions"
