name: golang-action-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
jobs:
  golang-test-action:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{matrix.platform}}
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on

    steps:
      # Install go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      # Build code
      - name: Build
        working-directory: ./src/github.com/${{ github.repository }}
        run:  make build
      # Run code
      - name: Run code
        working-directory: ./src/github.com/${{ github.repository }}
        run: make run
        env:
          GREETING: "from git actions"